# .github/linter.yml

# Atur pengaturan linter
linters:
  php:
    # Menonaktifkan pengecekan untuk file dengan ekstensi .myphp
    ignore:
      - "**/*.myphp"
      - "UndefinedClass" # Mengabaikan kesalahan UndefinedClass
      - "UndefinedGlobalVariable" # Mengabaikan kesalahan UndefinedGlobalVariable
