name: Super-Linter

on: 
  push:

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Tambahkan langkah untuk menginstall PHP dan ekstensi mysqli
      - name: Setup PHP with required extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' # Sesuaikan dengan versi PHP yang Anda gunakan
          extensions: mysqli

      # Jalankan Super-Linter
      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
